name: sages-ml-2026-02-07
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - bzip2=1.0.8=h500dc9f_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - libblas=3.11.0=5_he492b99_openblas
  - libcblas=3.11.0=5_h9b27e0a_openblas
  - libcxx=21.1.8=h4fb565c_2
  - libexpat=2.7.3=heffb93a_0
  - libffi=3.5.2=hd1f9c09_0
  - libgcc=15.2.0=h08519bb_17
  - libgfortran=15.2.0=h7e5c614_17
  - libgfortran5=15.2.0=hd16e46c_17
  - liblapack=3.11.0=5_h859234e_openblas
  - liblzma=5.8.2=h11316ed_0
  - libmpdec=4.0.0=hf3981d6_1
  - libopenblas=0.3.30=openmp_h6006d49_4
  - libsqlite=3.51.2=hb99441e_0
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=21.1.8=h472b3d1_0
  - ncurses=6.5=h0622a9a_3
  - numpy=2.4.2=py314h9089906_1
  - openssl=3.6.1=hb6871ef_1
  - pandas=3.0.0=py314h7192283_0
  - pip=26.0.1=pyh145f28c_0
  - python=3.14.3=h994187b_0_cp314t
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.14=8_cp314t
  - readline=8.3=h68b038d_0
  - six=1.17.0=pyhe01879c_1
  - tk=8.6.13=h7142dee_3
  - tzdata=2025c=hc9c84f9_1
  - zstd=1.5.7=h3eecb57_6
prefix: /usr/local/Caskroom/miniconda/base/envs/sages-ml-2026-02-07
